### ISSUE TITLE
The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0

### ISSUE THREAD

**Issue by CybotTM** [netresearch/timetracker#10]
The "security.context" service is deprecated since Symfony 2.6 and will be removed in 3.0

The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0

**Comment by CybotTM** [comment]
fixed

**Comment by rcheapizote** [comment]
Same problem here, how did you fix this?
