### ISSUE TITLE
Segfaults with OAuth extension

### ISSUE THREAD

**Issue by CybotTM** [netresearch/timetracker#26]
i get segfaults on oauth->fetch() calls

CLI: randomly
FPM: always

OAuth 2.0.3 installed by pecl install oauth
PHP docker container php/7-fpm

tested with PHP 5.6, 7.1, 7.2
tested with and without opcache

Detailed PHP setup: https://github.com/netresearch/timetracker/blob/merge-master-u2/Dockerfile

**Comment by CybotTM** [comment]
Hi @cweiske or @nemesis621 ,

can you please be so kind and share your PHP environment with me?

- OS and version?
- PHP version?
- install method? built from sources or packages by OS distro
- PHP extensions installed/enabled

Thank you

**Comment by cweiske** [comment]
We're running  PHP Version 5.6.38-0+deb8u1, installed via apt on debian:jessie

**Comment by CybotTM** [comment]
Thank you.
