### ISSUE TITLE
  The path "hwi_oauth.resource_owners.jira.client_id" cannot contain an empty value, but got "".

### ISSUE THREAD

**Issue by CybotTM** [netresearch/timetracker#3]
running composer install produces following error:

 The path "hwi_oauth.resource_owners.jira.client_id" cannot contain an empty value, but got "".
  The path "hwi_oauth.resource_owners.jira.client_secret" cannot contain an empty value, but got "".

jira_client_id should be an optional setting

**Comment by CybotTM** [comment]
@nemesis621 can you have a look into this?

**Comment by nemesis621** [comment]
You are totally right. I'm going to fix this issue asap.

**Comment by CybotTM** [comment]
just wait a moment, i will push update to Symfony 2.8 to master in a couple if moments

**Comment by CybotTM** [comment]
ok, master is up to date.

**Comment by nemesis621** [comment]
This this should be fixed. See the answer in issue https://github.com/netresearch/timetracker/issues/11 for more information.

**Comment by CybotTM** [comment]
thank you
