### ISSUE TITLE
automatic creating new users should be optional/configurable

### ISSUE THREAD

**Issue by CybotTM** [netresearch/timetracker#4]
automatic creating new users feature should be optional/configurable

**Comment by CybotTM** [comment]
@nemesis621 would be nice if can have a look into this.

**Comment by nemesis621** [comment]
Good Point. Haven't thought of it. I'm going to implement this.

**Comment by CybotTM** [comment]
just wait a moment, i will push update to Symfony 2.8 to master in a couple if moments

**Comment by nemesis621** [comment]
@CybotTM this issue is fixed in the current version of mogic-le/timetracker master
