### ISSUE TITLE
typo in oauh_area

### ISSUE THREAD

**Issue by CybotTM** [netresearch/timetracker#5]
typo in "oauh_area", should be "oauth_area"

**Comment by CybotTM** [comment]
@nemesis621 if you have the time, it would be nice if you could also have a look into this, thank you very much.

**Comment by nemesis621** [comment]
I will. thank you for the hint.

**Comment by nemesis621** [comment]
@CybotTM this issue is fixed in the current version of mogic-le/timetracker master
