### ISSUE TITLE
PHP Warning:  constant(): Couldn't find constant arguments in vendor/ci/restclientbundle/Circle/RestClientBundle/DependencyInjection/CircleRestClientExtension.php on line 54

### ISSUE THREAD

**Issue by CybotTM** [netresearch/timetracker#6]
when running composer install or in web frontend:

PHP Warning:  constant(): Couldn't find constant arguments 
in vendor/ci/restclientbundle/Circle/RestClientBundle/DependencyInjection/CircleRestClientExtension.php 
on line 54

**Comment by CybotTM** [comment]
@nemesis621 if you have the time, it would be nice if you could also have a look into this, thank you very much.

**Comment by nemesis621** [comment]
@CybotTM this issue is fixed in the current version of mogic-le/timetracker master
